services:
  swagger:
    image: swaggerapi/swagger-ui
    ports: ["8080:8080"]
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi/openapi.yaml:/openapi.yaml:ro

  mock:
    image: stoplight/prism:4
    command: ["mock", "-h", "0.0.0.0", "/openapi.yaml"]
    ports: ["4010:4010"]
    volumes:
      - ./openapi/openapi.yaml:/openapi.yaml:ro